### PR TITLE
Add annotation var for .texNameAnnotations path

### PR DESCRIPTION
**Pull request by lorcanj**
Not sure if this is what you meant, please let me know if this is not quite correct. Thanks

### CODE REVIEW

**Comment by christianp** [comment]
@lorcanj that line of code doesn't do anything. 

In [`jme-display.js`](https://github.com/numbas/Numbas/blob/master/runtime/scripts/jme-display.js#L931) there's a dictionary containing functions that produce LaTeX code for different variable name annotations. #770 asks to add another entry to this dictionary for the annotation `'diff'`, which would return `'{\\mathrm{d}'+name+'}'`.

**Comment by lorcanj** [comment]
Oof, my bad! I've removed that variable previosuly added and added that dictionary entry to the correct file.

**Comment by christianp** [comment]
That's it! Thank you very much for this contribution; I've merged it.

Could you add yourself to the CONTRIBUTORS.md file, please?

**Comment by christianp** [comment]
Thanks! I've merged in your commits, omitting the ones that changed jme-variables.js. 

If you want another job to do, #690 asks to recognise unicode symbol equivalents of operator and function names. There are plenty of these, so you could add a few.

**Pull request closed without merging**
