### PR TITLE
Issue 506: Some options for what's shown on the results page

### PR DESCRIPTION
**Pull request by stuwilmur**
**Background**
Compiler changes to support option not to show the questions and advice on the printed version of the results page.

Accompanies [Numbas/editor#799](https://github.com/numbas/editor/pull/799)

**Changes**
- Add handling for new `resultsshowquestions` and  `resultsshowadvice` options in Exam.py, exam.js
- Add new selectors for new classes in exam.css for printing
- Add handling to apply additional css classes to display-base.js

**Discussion**
The new classes have perhaps not gone in to the most appropriate viewmodel.

### CODE REVIEW

**Comment by stuwilmur** [comment]
Hello @christianp, just a friendly note that this PR and its [sibling](https://github.com/numbas/editor/pull/799) are open for review, in case you missed them 🙂.

**Comment by christianp** [comment]
@stuwilmur thanks, I'm aware of this and will get round to looking at it. I'm very busy at the moment, sorry!
Is this urgent for you?

**Comment by stuwilmur** [comment]
@christianp, Thank you; there is no need to apologise: there is absolutely no urgency! I just wanted to check it hadn't slipped through the net.

**Comment by christianp** [comment]
I've finally got round to reviewing this!
I had to cherry-pick the commits to avoid a huge merge conflict, so GitHub doesn't know I've merged this in. Thanks!

**Pull request closed without merging**
