### PR TITLE
Adding the option to shuffle question groups

### PR DESCRIPTION
**Pull request by arm61**
I believe that this deals with the first bullet point in #525. Would be awesome if someone could confirm this is the right track before I tackle the second bullet point (my js is a bit rusty so it isn't necessarily as straightforward as this). Cheers

### CODE REVIEW

**Comment by christianp** [comment]
Thanks for this. Looks good to me! Let me know if you need help with the second part.

**Comment by arm61** [comment]
Thanks for checking over this. I am trying to make the appropriate changes in ```runtime/scripts/exam.js```, I have added the getting of the ```shuffleQuestionGroups``` and created this as a property in the Exam prototype. However, I am trying to use Numbas.math.deal function to randomise but is it then necessary to get the number of question groups too?

Sorry for being pretty useless :smile:

**Comment by christianp** [comment]
The number of groups will be `this.question_groups.length`.

You need to keep track of the original order of the question groups, and the shuffled order. Lots of code relies on `Exam.question_groups` being the list of groups in the order they're displayed, so that should be the shuffled list.

**Comment by christianp** [comment]
This has been resolved by #693.

**Pull request closed without merging**
