### PR TITLE
Trig simplification

### PR DESCRIPTION
**Pull request by JessicaEB**
I've added some simplification rules and some tests. The tests are showing some behaviour I can't make sense of.

### CODE REVIEW

**Comment by christianp** [comment]
`0^0` is a good catch! I'll try to test this tomorrow.

**Comment by JessicaEB** [comment]
I have put in a rule that will sort the errors provided you don't care about too many decimal places. I would support keeping pi separate from numbers in general. As it is, pi doesn't always get changed to a decimal, only in certain situations. Generally I think it would be nice to have an option to turn numbers to decimals at the end, although I don't know how you would interpret decimals put in if you want to work with fractions. I can't think of a way pi could get into a formula without being explicit, but I may have not thought of something. 

I don't know whether there are people using the system who need very precise decimals. Also, I'm not certain where the error is being introduced. Clearly the system is correctly identifying the input as an integer fraction of pi, which makes me think the error is more likely to be coming from the evaluation. If that's the case, changing the input format won't help.

**Comment by christianp** [comment]
Adding a simplification rule to round near-integers is a very good idea. I'd been thinking of changing the rules like `unitFactor` to look for "close enough to 1", but doing that in a separate rule is definitely better.

One way pi can creep in is through functions like arcsin.

You definitely need to keep as much precision as you can. Errors accumulate surprisingly quickly; we have stats questions asking for answers to 2 or 3 decimal places which behave surprisingly if you don't round off at exactly the right points. I also have a colleague in chemistry who wants to work with numbers on the order of 10^-12, which will need better handling of precision than the standard floats Numbas currently uses.

The errors you've seen are coming from the evaluation of things like `tan(pi/4)` - you get a number close to, but not exactly, 1, because the calculated value of `pi/4` is very slightly imprecise. The display code rounds numbers to about 15 d.p., but internally they're not quite the right value.

In other news, yesterday I started playing around with extending the pattern-matching syntax to make things easier. I have a branch at [christianp/Numbas@trig-rules](https://github.com/christianp/Numbas/tree/trig-rules) which extends the `;` operator to let you give a default value for a term which doesn't appear. For example, `m_any(m_number;a * pi, pi;a:1)` will capture `a*pi`, setting `a=1` when there's no product. That should make it possible to write one rule to do a particular rewrite instead of several, for different combinations of coefficients being present.

**Comment by christianp** [comment]
Is there an easy subset of these rules that can be merged in now? I think the stuff around `0^0` can definitely go in.

I've gone back and forth on the trig rules a few times: rounding errors make matching raw numbers quite erratic, but is there much point in matching symbolically? Did this come about because of a specific question you were working on?

**Comment by JessicaEB** [comment]
The odd/even rules function fine I believe, although they will do more when factorising works. Not the common factors. I hope to get back to this soon.

**Comment by christianp** [comment]
I wasn't happy with the new syntax. It didn't do a very good job of reducing repetition, in the end. I think we might need to radically rethink how the rewriting rules work.

**Comment by JessicaEB** [comment]
Ok, here's an opening gambit (aiming to follow the symbols already in use).

';m_number,;n_real:1,;r:0' , 'cos(n*pi)/m+r' (etc)

First list the variables you want to use, each of which might have a type and/or a default value; then give the statement; the matching algorithm runs through all subsets of the default values, subs them into the formula and then...

Can you bootstrap the rules? As in, run the earlier rules on the later ones to build up a big set of rules from a shorter list? Part of the problem currently is that you have to undo any rules that might have been applied earlier, but rearranging the rules won't solve the problem because the user could have input something with any arrangement.

**Comment by christianp** [comment]
Bootstrapping the rules is a good idea, but I suppose it's computationally equivalent to changing the way that matches are decided.
For example, if regular expression syntax didn't have the quantifier `{from,to}`, then something like `a{1,2}` could be "bootstrapped" to two rules `a` and `aa`. Instead, the interpreter produces the same behaviour while interpreting the original rule.
I'm concerned you'd get a combinatorial explosion by trying to expand rules in advance.

I think the real awkwardness in our current syntax is dealing with optional terms. Your example above could be `m_any( cos(n*pi)/m, cos(n*pi)/m + r)` to deal with `r` being present or not, but it requires you to repeat the rest of the expression. It would be good to have something like `m_number + m_maybe(m_number,0)`, which would match either a single number or the sum of two numbers. I'm not sure how it would work, though: what would `(?;a + ?;b) + m_maybe(?;c,0)` do?

**Comment by JessicaEB** [comment]
I don't understand your first paragraph.
Actually what I was thinking of was to have a separate program that writes the rules for us (perhaps in the original notation) by expanding out more the condenced notation, although I thought that might not be sensible to do in a single step. I think to some extent the combinatorial explosion is inherent in the way the possible inputs need to be simplified, at least if the formula-storage-tree stays as it is. Even if the sepatate program was fairly slow, it wouldn't need running that often.

**Comment by christianp** [comment]
My point was that whatever you can get a rule-writing program to do, you can change the rule interpreter to produce the same behaviour.

**Comment by christianp** [comment]
I'm closing this because the pattern-matching system has been rewritten since this pull request was opened.

**Pull request closed without merging**
