### PR TITLE
Removed submit part for questions with one part

### PR DESCRIPTION
**Pull request by RingoKid**
#573

### CODE REVIEW

**Comment by RingoKid** [comment]
Thanks for the quick feedback. Please check the latest commit.

**Comment by christianp** [comment]
Looks good! I've squashed all your commits together and merged them in. Thanks!

**Comment by RingoKid** [comment]
Thanks a lot. This was my first PR ever and it was fun. I'd like to do more.

**Comment by RingoKid** [comment]
I've done everything according to the instructions but when I press 'Test Run', it takes me to a new tab and gives a 'Page Not Found' error. But a new file inside static/previews is created with index.html. How would you fix that?

**Comment by christianp** [comment]
@RingoKid probably best to take this to email: I'm christian.perfect@ncl.ac.uk.

**Pull request closed without merging**
